const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let cut=12, selected=new Set(), activeGate=null;

function protocolFor(c){return c>=9?'v3':c>=6?'v2':'v1'}
async function api(url,opt={}){const r=await fetch(url,opt),t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{throw Error('Invalid API response')}if(!r.ok)throw Error(d.detail||d.message||'API error');return d}
function trace(m){const x=$('trace');if(!x)return;x.innerHTML+='<p>'+m+'</p>';x.scrollTop=x.scrollHeight}
function modal(id,on=true){$(id)?.classList.toggle('hidden',!on)}
function currentCut(){return +($('cut')?.value||12)}
function statusDot(s){return s==='clinical'?'clinical':s==='missing'?'missing':'ok'}

async function loadRoster(){
 const d=await api('/api/roster?cut='+cut); $('rosterCount').textContent=d.subjects.length+' subjects';
 const q=($('rosterSearch').value||'').toLowerCase();
 const groups={}; d.subjects.filter(x=>x.usubjid.toLowerCase().includes(q)||x.site.toLowerCase().includes(q)).forEach(x=>(groups[x.site]??=[]).push(x));
 $('rosterList').innerHTML=Object.entries(groups).map(([site,rows])=>'<div class="sitegroup"><b>SITE '+esc(site)+'</b>'+rows.map(x=>'<label class="rosterrow"><input type="checkbox" data-subject="'+esc(x.usubjid)+'" '+(selected.has(x.usubjid)?'checked':'')+'><i class="dot '+statusDot(x.status)+'"></i><span>'+esc(x.usubjid)+'</span><em>'+esc(x.status.toUpperCase())+'</em></label>').join('')+'</div>').join('');
 document.querySelectorAll('.rosterrow input').forEach(i=>i.addEventListener('change',()=>{i.checked?selected.add(i.dataset.subject):selected.delete(i.dataset.subject); updateSelection()}));
}
function updateSelection(){ $('compareBtn').classList.toggle('hidden',selected.size<2); document.querySelectorAll('.rosterrow input').forEach(i=>i.checked=selected.has(i.dataset.subject)); if(selected.size===1)focusSubject([...selected][0]); if(selected.size>=2)compareSubjects([...selected].slice(0,3));}
async function focusSubject(subject){
 selected=new Set([subject]); await loadRoster();
 const p=await api('/api/patient/'+encodeURIComponent(subject)+'?cut='+cut); renderPatient(p);
 trace('<b>[patient360]</b> loaded '+esc(subject));
}
function renderPatient(p){
 $('macro').classList.add('minimap'); $('patientStage').classList.remove('hidden'); $('stageMode').textContent='ACTIVE VIEW'; $('stageTitle').textContent='PATIENT 360 · '+p.usubjid; $('macroBtn').classList.remove('hidden');
 const dm=(p.domains?.DM||[])[0]||{}, ae=p.domains?.AE||[], lb=p.domains?.LB||[], ex=p.domains?.EX||[];
 const alerts=ae.filter(r=>String(r.AESER).toUpperCase()==='Y'||String(r.AESHOSP).toUpperCase()==='Y');
 const timeline=[...ex.map(r=>({d:r.EXSTDTC||r.EXENDTC||'',t:'DOSE',v:(r.EXDOSE||'')+' '+(r.EXDOSU||'')})),...ae.map(r=>({d:r.AESTDTC||'',t:'ADVERSE EVENT',v:r.AETERM||''}))].sort((a,b)=>String(a.d).localeCompare(String(b.d)));
 $('patientStage').innerHTML='<div class="patienthead"><div><small>PATIENT 360</small><h1>'+esc(p.usubjid)+'</h1><p>SITE '+esc(dm.SITEID||'—')+' · '+esc(dm.SEX||'—')+' · AGE '+esc(dm.AGE||'—')+'</p></div><span class="statuspill '+(alerts.length?'critical':'safe')+'">'+(alerts.length?'CLINICAL ALERT':'MONITORING')+'</span></div><div class="demorow"><div><small>SEX</small><b>'+esc(dm.SEX||'—')+'</b></div><div><small>AGE</small><b>'+esc(dm.AGE||'—')+'</b></div><div><small>SITE</small><b>'+esc(dm.SITEID||'—')+'</b></div><div><small>AE COUNT</small><b>'+ae.length+'</b></div><div><small>DOSE RECORDS</small><b>'+ex.length+'</b></div></div><div class="patientgrid"><section><div class="cardtitle">SYNCHRONIZED TIMELINE</div><div class="timeline2">'+(timeline.length?timeline.map(x=>'<div><i></i><small>'+esc(x.d)+'</small><b>'+esc(x.t)+'</b><span>'+esc(x.v)+'</span></div>').join(''):'<div class="empty">No EX or AE events at this cut.</div>')+'</div></section><section><div class="cardtitle">LAB RESULTS</div><div class="labgrid">'+lb.slice(-30).map(r=>'<div><b>'+esc(r.LBTEST||'LAB')+'</b><span>'+esc(r.LBORRES??r.LBSTRESN??'—')+' '+esc(r.LBORRESU||r.LBSTRESU||'')+'</span><small>'+esc(r.LBDTC||'')+'</small></div>').join('')+'</div></section></div>';
 $('evidenceTitle').textContent='Evidence · '+p.usubjid;
 $('evidenceContent').innerHTML='<div class="evidencebox"><b>Patient 360 source domains</b><p>'+Object.entries(p.domains||{}).map(([k,v])=>k+' '+v.length+' records').join(' · ')+'</p></div>';
}
async function compareSubjects(ids){$('macro').classList.add('minimap');$('patientStage').classList.remove('hidden');$('stageMode').textContent='COMPARE';$('stageTitle').textContent='PATIENT COMPARISON';$('macroBtn').classList.remove('hidden');const ps=await Promise.all(ids.map(x=>api('/api/patient/'+encodeURIComponent(x)+'?cut='+cut)));$('patientStage').innerHTML='<div class="comparegrid">'+ps.map(p=>{const dm=(p.domains?.DM||[])[0]||{},lb=p.domains?.LB||[];return '<section class="comparecard"><small>SUBJECT</small><h2>'+esc(p.usubjid)+'</h2><p>Site '+esc(dm.SITEID||'—')+' · Age '+esc(dm.AGE||'—')+' · Sex '+esc(dm.SEX||'—')+'</p><div class="labgrid">'+lb.slice(-12).map(r=>'<div><b>'+esc(r.LBTEST||'LAB')+'</b><span>'+esc(r.LBORRES??r.LBSTRESN??'—')+' '+esc(r.LBORRESU||r.LBSTRESU||'')+'</span></div>').join('')+'</div></section>'}).join('')+'</div>'}
function returnGraph(){selected.clear();$('macro').classList.remove('minimap');$('patientStage').classList.add('hidden');$('macroBtn').classList.add('hidden');$('compareBtn').classList.add('hidden');$('stageMode').textContent='MACRO NAVIGATOR';$('stageTitle').textContent='3D ORBITAL KNOWLEDGE GRAPH';loadRoster()}
async function query(q,title=q){modal('queryModal');$('queryTitle').textContent=title;$('queryAnswer').textContent='Querying StudyGraph…';$('lookupSubjects').textContent='';$('queryEvidence').textContent='';try{const d=await api('/api/query?q='+encodeURIComponent(q)+'&cut='+cut);$('queryAnswer').textContent=d.text||d.answer?.join(', ')||'No answer returned.';$('lookupSubjects').innerHTML=(d.answer||[]).filter(x=>/^042-S\d{2}-\d{3}$/.test(String(x))).map(x=>'<button class="subjectlink" data-subject="'+esc(x)+'">'+esc(x)+'</button>').join('')||'No subject IDs in answer.';$('queryEvidence').innerHTML=(d.evidence||[]).map(e=>'<div class="evidenceLine"><b>'+esc(e.domain||'DOC')+'</b> · '+esc(e.usubjid||e.document||'')+(e.seq!=null?' · seq '+e.seq:'')+'</div>').join('')||'No source records returned.';document.querySelectorAll('.subjectlink').forEach(b=>b.onclick=()=>{modal('queryModal',false);focusSubject(b.dataset.subject)});trace('<b>[query]</b> '+esc(title)+' · '+(d.evidence?.length||0)+' evidence records')}catch(e){$('queryAnswer').textContent=e.message}}
async function loadStats(){const d=await api('/api/stats?cut='+cut);$('protocol').textContent=protocolFor(cut);$('scrubLabel').textContent='CUT '+cut+' · PROTOCOL '+protocolFor(cut);$('pending').textContent=d.pending??0}
async function gate(){modal('gateModal');const d=await api('/api/escalations?cut='+cut);activeGate=d.escalations?.[0]||null;if(!activeGate){$('gateCode').textContent='No pending escalation';$('gateBody').innerHTML='<p class="empty">All escalations at this cut have been handled.</p>';return}$('gateCode').textContent=activeGate.code;$('gateBody').innerHTML='<div class="evidencebox"><b>'+esc(activeGate.usubjid||'Site-level')+'</b><p>'+esc(activeGate.summary||'')+'</p><code>'+esc((activeGate.evidence||[]).map(e=>e.domain+' · '+(e.usubjid||'')+' · seq '+(e.seq??'')).join(' | '))+'</code></div>'}
async function gateDecision(decision){if(!activeGate)return;await api('/api/gate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cut,code:activeGate.code,usubjid:activeGate.usubjid,decision,reason:'Decision recorded in ATLAS Human Gate.'})});modal('gateModal',false);trace('<b>[human_gate]</b> '+decision+' '+esc(activeGate.code));loadStats()}
function bindGraph(){document.querySelectorAll('.subject').forEach(n=>n.onclick=()=>focusSubject(n.dataset.subject));document.querySelectorAll('.site').forEach(n=>n.onclick=()=>query(n.textContent.trim()==='S07'?'Which subjects have Hy’s Law findings?':n.textContent.trim()==='S02'?'Which subjects have serious adverse events?':'What findings are present?','Site '+n.textContent.trim()+' intelligence'));document.querySelectorAll('.sat').forEach(n=>n.onclick=()=>query(n.textContent.trim()==='AE'?'Which subjects have serious adverse events?':'Which subjects have Hy’s Law findings?',n.textContent.trim()+' signal'));$('aeNode').onclick=()=>query('Which subjects have serious adverse events?','Adverse Event · Cellulitis');document.querySelector('.core').onclick=()=>query('What protocol version is active at the selected cut?','Protocol Intelligence')}
function bind(){ $('initialize').onclick=()=>{ $('boot').classList.add('hidden');$('app').classList.remove('hidden');trace('<b>[system]</b> ATLAS initialized · loading StudyGraph');loadRoster();loadStats();bindGraph()};$('cut').onchange=async()=>{cut=currentCut();$('scrubber').value=cut;await loadRoster();await loadStats();returnGraph()};$('scrubber').oninput=()=>{$('cut').value=$('scrubber').value;cut=currentCut();$('scrubLabel').textContent='CUT '+cut+' · PROTOCOL '+protocolFor(cut)};$('scrubber').onchange=async()=>{await loadRoster();await loadStats();returnGraph()};$('rosterSearch').oninput=loadRoster;$('clearSelect').onclick=()=>{selected.clear();loadRoster();returnGraph()};$('macroBtn').onclick=returnGraph;$('compareBtn').onclick=()=>compareSubjects([...selected].slice(0,3));$('askQuestion').onclick=()=>query($('questionInput').value.trim());$('questionInput').onkeydown=e=>{if(e.key==='Enter')query(e.target.value.trim())};$('help').onclick=()=>modal('helpModal');$('bell').onclick=gate;$('cycle').onclick=async()=>{trace('<b>[system]</b> Monitor cycle running…');$('traceStatus').textContent='RUNNING';try{const d=await api('/api/cycle?cut='+cut);trace('<b>[execute]</b> '+(d.stats?.findings??0)+' findings · '+(d.stats?.escalations??0)+' escalations');$('traceStatus').textContent='COMPLETE';await loadStats()}catch(e){trace('<b>[error]</b> '+esc(e.message));$('traceStatus').textContent='ERROR'}};$('reject').onclick=()=>gateDecision('REJECTED');$('approve').onclick=()=>gateDecision('APPROVED');$('clarify').onclick=()=>gateDecision('CLARIFY');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>modal(b.dataset.close,false));document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.add('hidden')})}
bind();
